name: cypress_hello_world
on:
  workflow_dispatch:

jobs:
  Cypress_Runner:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./
  
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Install npm
        working-directory: Cypress_Tests
        run: npm install cypress --save-dev

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: Cypress_Tests
          spec: e2e/**.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}




    